### ISSUE TITLE
SSH failed - expected host key does not match

### ISSUE THREAD

**Issue by kixmto** [zhbjsh/homeassistant-ssh#9]
Hi there,

I am running the SSH integration on HASS OS and I added a host successfully with the integration for testing. After a while I reinstalled an Pi Os image on the host and since then I am not able to connect to the host again. I get the following error:

SSH connection failed (Host key for server '192.168.0.x' does not match: got 'abc', expected 'xyz').

Makes sense, since the image changed, hence the key files also changed. I wanted to delete the host key file on HASS OS but there is no file in ~/.ssh/known_hosts. I tried it in different locations, with root but had no success. The known_hosts file does not exist.

There is a known_hosts file in /homeassistant(config) and it shows a different host that I added to the integration, but not the one with the mismatch.

Any ideas?
Thanks in regards!

**Comment by mhoogenbosch** [comment]
The known_hosts file inside the config folder should be the correct one. I have experienced this a couple of times before, and it works just fine for me removing the line within the file.

Would be a nice addition if you would get a question rasied if you want to overwrite the entry.

**Comment by OverZealous** [comment]
Followup: I'm running out of ideas at this point. I've removed the key from just about every single file it could exist on, removed and reinstalled the integration, and rebooted the OS. I'm out of places to check for where it's cached this host key, and I can no longer connect to my device.

I modified the SSH component to print out the `known_hosts` file name and contents, and it's loading the correct file. I can see the contents change—I can even see the correct key within the file once I manually add it (it shows the empty array before, then the correct info after):

```
Logger: custom_components.ssh.config_flow
Source: custom_components/ssh/config_flow.py:495
integration: ssh ([documentation](https://github.com/zhbjsh/homeassistant-ssh), [issues](https://github.com/zhbjsh/homeassistant-ssh/issues))
First occurred: 2:51:04 PM (2 occurrences)
Last logged: 2:52:13 PM

    []
    ['192.168.1.105 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBG/ytEmKSLda9LsY/bLiANMNFHWltnW/AaPmvD1ZXdnnH5WeaUxvTP6iHufE67QIFZgmxROrIGJeI4UX4/bOr9U=\n', '\n']
```

Yet immediately after this, the SSH connection fails:

```
This error originated from a custom integration.

Logger: custom_components.ssh.config_flow
Source: custom_components/ssh/config_flow.py:576
integration: ssh (documentation, issues)
First occurred: 2:51:05 PM (2 occurrences)
Last logged: 2:52:14 PM

SSH connection failed (Host key for server '192.168.1.105' does not match: got 'AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBG/ytEmKSLda9LsY/bLiANMNFHWltnW/AaPmvD1ZXdnnH5WeaUxvTP6iHufE67QIFZgmxROrIGJeI4UX4/bOr9U=', expected 'AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBF3g1fIiEb+4X6YmIjSpP5PJ0U+Z/24wwc46hd8lrV3Iz/eKYkQdpgfemZIYmInOcEkRC/QEgv/aDVJ9Lh9cY+M=')
```

Hopefully someone can help, because at this point the only solution I can come up with is to change the IP of my device, which is bonkers.

**Comment by OverZealous** [comment]
I figured it out! I had also configured some shell commands, and since these also use SSH, it apparently added a key to `/root/.ssh/known_hosts`, which is not accessible to the normal login for HA.

I ended up adding an additional `shell_command` for `ssh-keygen -R <IP>`, which I can run manually to remove the key from this hidden file, and it allowed me to access the device again.

**Comment by puerto-rico** [comment]
> I figured it out! I had also configured some shell commands, and since these also use SSH, it apparently added a key to `/root/.ssh/known_hosts`, which is not accessible to the normal login for HA.
> 
> I ended up adding an additional `shell_command` for `ssh-keygen -R <IP>`, which I can run manually to remove the key from this hidden file, and it allowed me to access the device again.


same issue here,  can you explain what you did to fix this ? 

i have a empty folder on  /root/.ssh/

**Comment by OverZealous** [comment]
@puerto-rico 

I added a shell command to reset the `known_hosts`, which looks like this:

```
shell_command:
  crestron_reset_host_key: ssh-keygen -R "192.168.1.106"
```

You'll have to restart HA for it to take effect. Make sure you change the IP address to your screen's address.

Then inside HomeAssistant, just run the new command using the developer tools. It has no arguments.

**Comment by zhbjsh** [comment]
Hi! Sorry to keep you waiting... 

Since version 0.9.8 you can choose to ignore the system host keys (the one in `~/.ssh/known_hosts`) and only use the file generated by the integration. You can change the setting by clicking on the three dots in the device settings and then on _Reconfigure_ . The former behavior was indeed a bit confusing, I hope it makes more sense now!

**Comment by puerto-rico** [comment]
thanks, but i could not find out how to do this, i am just a basic user of HA.
But found a more simple solution, that i did not think of before.
i used the built  in "file editor" with that i could just edit the file.

Now the integration works again :)
